@startuml
'https://plantuml.com/sequence-diagram


autoactivate on
autonumber

actor "RegUser" as User
participant ":ReviewController" as Ctrl
participant ":ReviewService" as Service
participant "Product_API:" as Api
participant ":Review" as Review
participant ":ReviewRepository" as Repo


activate User

User -> Ctrl : POST/Review/{sku}/create/
Ctrl -> Service : create(ReviewDTO, sku)
Service -> Api : GET/8080/products?sku={}
Api --> Service : product
''Ver como obter userId
Service -> Review : newFrom (ReviewDTO,userId)
Review --> Service : review
Service -> Repo : save(review)
Repo --> Service : ok
Service --> Ctrl : ok
Ctrl --> User : ok

@enduml