@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":ReviewAPI" as rev1
participant ":Review" as rev2

activate User

User -> rev1: DELETE/{reviewId}/remove
rev1 -> rev2: DELETE/8086/{reviewId}/remove
rev2 -->rev1: String
rev1 --> User: String
@enduml