@startuml
'https://plantuml.com/sequence-diagram

autonumber

autoactivate on
autonumber

actor "User" as User
participant ":ReviewAPI" as rev1
participant ":Review" as rev2

activate User

User -> rev1: GET/reviews/pending
rev1 -> rev2: GET/8086/reviews/pending
rev2 -->rev1: Iterable<Reviews>
rev1 --> User: Iterable<reviews>
@enduml