@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":Review1" as rev1
participant ":Review2" as rev2

activate User

User -> rev1: GET/reviews/{sku}/rating
rev1 -> rev2: GET/8086/reviews/{sku}/product
rev2 -->rev1: List<Review>
rev1 --> User: RatingFrequency
@enduml