@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
hide circle
hide methods

class RegUser{
-UserId
-Name
-Password
-Email
-Address
-Role
}
class Review{
-ReviewId
-Text
-Rating
-Date
-Status
-upVote
-downVote
}

Moderator "1" -right-- "0..*" Review:  changes status  >
@enduml
