@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "RegUser" as User
participant ":ReviewController" as Ctrl
participant ":ReviewService" as Service
participant ":ReviewRepository" as Rep
participant ":Review" as rev
participant ":VotesApi" as Api

activate User


User -> Ctrl: DEL/review/{ReviewID}/remove
Ctrl -> Service: deleteReview(reviewId)
Service -> Api: GET/8082/votes/{reviewId}
Api --> Service: 0
Service -> Rep: getReviewById(reviewId)
Rep --> Service: review
Service ->Rep: delete(review)
Rep --> Service: ok
Service --> Ctrl: ok
Ctrl --> User: ok
@enduml
