@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":ReviewController" as Ctrl
participant ":ReviewService" as Service
participant ":ReviewRepository" as Rep
participant ":RatingFrequency" as RatFreq

activate User

User -> Ctrl: GET/review/{sku}/rating
Ctrl -> Service: getRatingFrequencyOfProduct(sku)
Service -> Rep: getReviewsByProduct(sku)
Rep --> Service: List
Service -> Rep: getAggregatedRating(sku)
Rep --> Service: globalRating
Service -> RatFreq : new
RatFreq --> Service: ratingFrequency
Service --> Ctrl: ratingFrequency
Ctrl --> User: ratingFrequency

@enduml
