@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
-UserId
-Name
-Password
-Email
-Address
-Role
}

class Review{
-ReviewId
-Text
-Rating
-Date
-Status
-upVote
-downVote
}

User "1" -right-- "0..*" Review: makes  >
@enduml
